url: http://rogeralsing.github.io
title: Roger on Azure
author: Roger Johansson
email: hi@rogeronazure.om
github_url: https://github.com/rogeralsing
issues_url: https://github.com/rogeralsing
twitter_handle: rogeralsing
twitter_url: https://twitter.com/rogeralsing
stack_overflow_url: http://stackoverflow.com/questions/tagged/azure
facebook_url: https://www.facebook.com/rogeralsing
google_group_url: https://groups.google.com/forum/#!forum/akkadotnet-user-list
logo_path: /images/akkalogo.png
bootcamp_url: abc
gitter_url: abc
